version: '3.8'
services:
  # redis-compose:
  #   image: redis
  #   command: redis-server --requirepass SUASENHA --appendonly yes
  #   hostname: redis
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - /home/duducp/Redis:/var/lib/postgresql/data
  #   networks:
  #     - fit
  db-mysql-fit:
    container_name: db-mysql-fit-container
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tutilabs-fit
      MYSQL_PASSWORD: password
    ports:
      - '3301:3306'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - fit
  # api:
  #   container_name: api-container-fit
  #   image: node:12
  #   working_dir: /usr/src/api-node-fit
  #   restart: always
  #   depends_on:
  #     - db-mysql-fit
  #   command: bash -c "npm install --only=prod && npm run debug"
  #   volumes:
  #     - ./dist/:/usr/src/clean-node-api/dist/
  #     - ./package.json:/usr/src/clean-node-api/package.json
  #   ports:
  #     - '6001:6001'
  #   networks:
  #     - fit
networks:
  fit:
    driver: bridge
