export const css = {
  all: `margin: 0; border: none; box-sizing: border-box; font-family: 'Roboto', sans-serif;`,
  body: `width: 100vw; height: 100vh; color: #636363;`,
  table_th_td: 'border: 1px solid #636363; border-collapse: collapse;',
  title: `width: 70%; height: 68.8px; text-align: center; font-size: 20.8px;`,
  title_date: `font-size: 16px; font-weight: bold;`,
  subtitle: `height: 68.8px; font-size: 16px;`,
  subtitle_td: `font-weight: 600; padding-left: 20px;`,
  content_td: `padding: 20px; border: none;`,
  content_table: `border: 2px solid #EDEDED; text-align: center; margin-bottom: 2rem;`,
  content_table_th: `border: none; height: 28px;`,
  footer: `border-bottom: 1px solid #000; width: 100%; height: 100px; display: flex; justify-content: space-around; align-items: center;`,
  footer_td: `text-align: right; padding-right: 20px; border: 2px solid transparent;`,
  image: `float: right; width: 167px; height: 50px; background-image: url('/assets/logo.png'); background-size: cover;`,
  imagelabs: `float: right; width: 121px; height: 50px; background-image: url('/assets/tutilabs.png'); background-size: cover;`,
}
